### ISSUE TITLE
Rename Document Uploads Wizard Step to "Supportive Documentation"

### ISSUE THREAD

**Issue by lamplus** [on-site/grantzilla#256] opened 2016-05-09 04:32 UTC
-   Change to Suportive Documentation Page
-   Add check list for needed supported documents

**Comment by scottjones** [comment] 2016-05-09 12:16
This is a duplicate of #242

**Comment by scottjones** [comment] 2016-05-23 14:51
Whoops, this is not the same thing...

**Comment by slinke** [comment] 2016-06-12 17:37
Where is this list of needed supported documents?

**Comment by scottjones** [comment] 2016-06-12 17:44
From https://github.com/on-site/grantzilla/files/175263/hif_online_application.pdf, which is listed on #240 

SUPPORTIVE DOCUMENTATION NEEDED FOR EVERY APPLICATION:
o Three‐month budget that demonstrates cash crisis and sustainability in future months
o W‐9 from landlord
o Relevant pages of lease (pages that show name of lessees, rental amount, security deposit amount, rental dates, and signatures of lessees and payee). If a lease has not been signed, an Acknowledgement to Rent can be submitted in lieu of lease
o Verification of owed costs (3‐Day Notice or other written verification of exactly what lessee owes)
o Verification of income for every adult (pay stubs, letter verifying employment, benefits award letter, etc)
o Verification of crisis (car repair bill, copy of no‐fault notice to vacate, verification of illness)

**Comment by ghost** [comment] 2016-06-12 17:55
Grazie! The uploaded files are not tagged as any particular type(that I can tell) right?  This is just going to be a static list.

**Comment by scottjones** [comment] 2016-06-12 17:58
That's a good place to start.  I think we'll want to start classifying the uploads at some point so it can be kind of a checklist.  Not sure what@joedean has done so far there, but believe he might have something started...

**Comment by scottjones** [comment] 2016-06-12 17:58
Thanks for jumping in to help!

**Comment by ghost** [comment] 2016-06-12 18:11
Heck yea!  :goberserk:

**Comment by slinke** [comment] 2016-06-12 18:17
Whoops, identity crisis.  Keep switching accounts  😭

**Closed as completed** 2016-06-12 22:17 UTC
